// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/mattreetz/Documents/Programming/LittlestLibrary/LittlestLibraryApp/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/mattreetz/Documents/Programming/LittlestLibrary/LittlestLibraryApp/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('/Users/mattreetz/Documents/Programming/LittlestLibrary/LittlestLibraryApp/index.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('LittlestLibrary', appParameters);
});